version: '3'
services:
  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - mongo_data:/db/data
volumes:
  mongo_data:
    driver: local
