name: Lint
on:
  push:
    paths:
      - 'testing/src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testing
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run prettier
      run: npm run lint:prettier
    - name: Run eslint
      run: npm run lint:eslint
